import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import { NextIntlClientProvider } from "next-intl";
import { TailwindToaster } from "@/components/shared/tailwind-toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = require(`../../../messages/${locale}.json`);
  return (
    <html lang={locale} data-theme="light">
      <Head>
        <link
          href="https://cdn.jsdelivr.net/npm/futura-font@1.0.0/styles.min.css"
          rel="stylesheet"
        />
      </Head>
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
          <TailwindToaster />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
